server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.92.140 #mongo主机 不写端口默认使用默认端口
      database: spitdb  #mongodb数据库
  redis:
    host: 192.168.92.140